{
    "A": {
        "queue": "short", 
        "resource": {
            "limit": {
                "max_virtual_memory": 20480
            }, 
            "require": {
                "min_proc": "4", 
                "temp_space": "5"
            }, 
            "reserve": {
                "memory": "20", 
                "temp_space": "5"
            }
        }
    }, 
    "B": {
        "queue": "short", 
        "resource": {
            "limit": {
                "max_virtual_memory": 20480
            }, 
            "require": {
                "min_proc": "4", 
                "temp_space": "5"
            }, 
            "reserve": {
                "memory": "20", 
                "temp_space": "5"
            }
        }
    }, 
    "C": {
        "queue": "short", 
        "resource": {
            "limit": {
                "max_virtual_memory": 20480
            }, 
            "require": {
                "min_proc": "4", 
                "temp_space": "5"
            }, 
            "reserve": {
                "memory": "20", 
                "temp_space": "5"
            }
        }
    }, 
    "D": {
        "queue": "short", 
        "resource": {
            "limit": {
                "max_virtual_memory": 20480
            }, 
            "require": {
                "min_proc": "4", 
                "temp_space": "5"
            }, 
            "reserve": {
                "memory": "20", 
                "temp_space": "5"
            }
        }
    }
}
